USE GTL
CREATE TABLE LibraryCard (
	CardNo NUMERIC(20) NOT NULL IDENTITY(1,1),
	IssueDate DATE NOT NULL,
	PRIMARY KEY (CardNo)
);
CREATE TABLE Person(
	SSN NUMERIC(20) NOT NULL,
	FName VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	HomeAddress VARCHAR(75),
	CampusAddress VARCHAR(75),
	CardNo NUMERIC(20) NOT NULL,
	PRIMARY KEY (SSN),
	FOREIGN KEY (CardNo) REFERENCES LibraryCard(CardNo) ON DELETE CASCADE
);
CREATE TABLE Librarian(
	SSN NUMERIC(20) NOT NULL,
	Position VARCHAR(50) NOT NULL,
	PRIMARY KEY (SSN),
	FOREIGN KEY (SSN) REFERENCES Person(SSN) ON DELETE CASCADE
);
CREATE TABLE Member(
	SSN NUMERIC(20) NOT NULL,
	Personification VARCHAR(50) NOT NULL,
	PRIMARY KEY (SSN),
	FOREIGN KEY (SSN) REFERENCES Person(SSN) ON DELETE CASCADE
);
CREATE TABLE PhoneNo(
	SSN NUMERIC(20) NOT NULL,
	Number INT NOT NULL,
	PRIMARY KEY (SSN, Number),
	FOREIGN KEY (SSN) REFERENCES Person(SSN) ON DELETE CASCADE
);
CREATE TABLE Item(
	ISBN NUMERIC(13) NOT NULL,
	Title VARCHAR(50) NOT NULL,
	Author VARCHAR(50),
	ItemDescription VARCHAR(50) NOT NULL,
	Publisher VARCHAR(50),
	YearPublishing INT,
	PRIMARY KEY (ISBN)
);
CREATE TABLE Map (
	ISBN NUMERIC(13) NOT NULL,
	NoCopies INT,
	PRIMARY KEY (ISBN),
	FOREIGN KEY (ISBN) REFERENCES Item(ISBN) ON DELETE CASCADE
);
CREATE TABLE Book (
	ISBN NUMERIC(13) NOT NULL,
	BookType VARCHAR(50) NOT NULL,
	PRIMARY KEY (ISBN),
	FOREIGN KEY (ISBN) REFERENCES Item(ISBN) ON DELETE CASCADE
);
CREATE TABLE BookCopy (
	ISBN NUMERIC(13) NOT NULL,
	Barcode NUMERIC(20) NOT NULL,
	PRIMARY KEY (ISBN, Barcode),
	FOREIGN KEY (ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE
);
CREATE TABLE BookSubject (
	ISBN NUMERIC(13) NOT NULL,
	BookSubject VARCHAR(50) NOT NULL,
	PRIMARY KEY (ISBN, BookSubject),
	FOREIGN KEY (ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE
);
CREATE TABLE Borrow (
	Id NUMERIC(20) NOT NULL IDENTITY(1,1),
	ISBN NUMERIC(13) NOT NULL,
	Barcode NUMERIC(20) NOT NULL,
	CardNo NUMERIC(20) NOT NULL,
	IsReturned BIT NOT NULL,
	DateBorrowed DATE NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (ISBN, Barcode) REFERENCES BookCopy(ISBN, Barcode) ON DELETE CASCADE,
	FOREIGN KEY (CardNo) REFERENCES LibraryCard(CardNo) ON DELETE CASCADE
);